// GHL merge fields, transcribed from HighLevel's official "List of Merge
// Fields" article (help.gohighlevel.com/support/solutions/articles/
// 48001078171-list-of-merge-fields).
//
// These are the tokens GHL resolves inside a custom value, SMS, or email. Which
// ones actually resolve depends on the sending context — an appointment token
// is empty unless the workflow is appointment-triggered — so the picker labels
// each group with that caveat rather than filtering.
//
// Account-specific tokens (this club's own custom values and contact custom
// fields) are NOT listed here; they come back live from the API and are merged
// in by the component.

export const MERGE_FIELD_GROUPS = [
  {
    key: 'contact',
    label: 'Contact',
    note: 'Resolves whenever the message is sent to a contact.',
    fields: [
      { token: '{{contact.name}}', label: 'Full name' },
      { token: '{{contact.first_name}}', label: 'First name' },
      { token: '{{contact.last_name}}', label: 'Last name' },
      { token: '{{contact.email}}', label: 'Email' },
      { token: '{{contact.phone}}', label: 'Phone' },
      { token: '{{contact.phone_raw}}', label: 'Phone (raw)' },
      { token: '{{contact.company_name}}', label: 'Company name' },
      { token: '{{contact.full_address}}', label: 'Full address' },
      { token: '{{contact.address1}}', label: 'Address line 1' },
      { token: '{{contact.city}}', label: 'City' },
      { token: '{{contact.state}}', label: 'State / region' },
      { token: '{{contact.postal_code}}', label: 'Postal code' },
      { token: '{{contact.timezone}}', label: 'Time zone' },
      { token: '{{contact.date_of_birth}}', label: 'Date of birth' },
      { token: '{{contact.source}}', label: 'Source' },
      { token: '{{contact.website}}', label: 'Website' },
      { token: '{{contact.id}}', label: 'Contact ID' },
    ],
  },
  {
    key: 'location',
    label: 'Account / Location',
    note: 'The sub-account (club) the message is sent from.',
    fields: [
      { token: '{{location.name}}', label: 'Account name' },
      { token: '{{location.full_address}}', label: 'Full address' },
      { token: '{{location.address}}', label: 'Address line 1' },
      { token: '{{location.city}}', label: 'City' },
      { token: '{{location.state}}', label: 'State / region' },
      { token: '{{location.country}}', label: 'Country' },
      { token: '{{location.postal_code}}', label: 'Postal code' },
      { token: '{{location.email}}', label: 'Email' },
      { token: '{{location.phone}}', label: 'Phone' },
      { token: '{{location.phone_raw}}', label: 'Phone (raw)' },
      { token: '{{location.website}}', label: 'Website' },
      { token: '{{location.logo_url}}', label: 'Logo URL' },
      { token: '{{location.id}}', label: 'Account ID' },
      { token: '{{location_owner.first_name}}', label: 'Owner first name' },
      { token: '{{location_owner.last_name}}', label: 'Owner last name' },
      { token: '{{location_owner.email}}', label: 'Owner email' },
    ],
  },
  {
    key: 'user',
    label: 'User (assigned staff)',
    note: 'The contact’s assigned user, or the user the workflow acts as.',
    fields: [
      { token: '{{user.name}}', label: 'Full name' },
      { token: '{{user.first_name}}', label: 'First name' },
      { token: '{{user.last_name}}', label: 'Last name' },
      { token: '{{user.email}}', label: 'Email' },
      { token: '{{user.phone}}', label: 'Phone' },
      { token: '{{user.phone_raw}}', label: 'Phone (raw)' },
      { token: '{{user.email_signature}}', label: 'Email signature' },
      { token: '{{user.calendar_link}}', label: 'Booking link' },
      { token: '{{user.call_provider_phone_number}}', label: 'External calling number' },
      { token: '{{user.call_provider_phone_number_raw}}', label: 'External calling number (raw)' },
    ],
  },
  {
    key: 'appointment',
    label: 'Appointment',
    note: 'Only resolves in appointment-triggered workflows (Day One, tours).',
    fields: [
      { token: '{{appointment.title}}', label: 'Title' },
      { token: '{{appointment.start_time}}', label: 'Start date & time' },
      { token: '{{appointment.only_start_date}}', label: 'Start date only' },
      { token: '{{appointment.only_start_time}}', label: 'Start time only' },
      { token: '{{appointment.end_time}}', label: 'End date & time' },
      { token: '{{appointment.only_end_date}}', label: 'End date only' },
      { token: '{{appointment.only_end_time}}', label: 'End time only' },
      { token: '{{appointment.day_of_week}}', label: 'Day of week' },
      { token: '{{appointment.month}}', label: 'Month number' },
      { token: '{{appointment.timezone}}', label: 'Time zone' },
      { token: '{{appointment.cancellation_link}}', label: 'Cancellation link' },
      { token: '{{appointment.reschedule_link}}', label: 'Reschedule link' },
      { token: '{{appointment.meeting_location}}', label: 'Meeting location' },
      { token: '{{appointment.notes}}', label: 'Notes' },
      { token: '{{appointment.add_to_calendar}}', label: 'Add-to-calendar link' },
      { token: '{{appointment.add_to_google_calendar}}', label: 'Google Calendar link' },
      { token: '{{appointment.add_to_ical}}', label: 'iCal / ICS link' },
      { token: '{{appointment.recurring.repeats}}', label: 'Recurring: repeats' },
      { token: '{{appointment.recurring.times_to_repeat}}', label: 'Recurring: times to repeat' },
      { token: '{{appointment.user.name}}', label: 'Assigned user name' },
      { token: '{{appointment.user.email}}', label: 'Assigned user email' },
      { token: '{{appointment.user.phone}}', label: 'Assigned user phone' },
      { token: '{{appointment.user.phone_raw}}', label: 'Assigned user phone (raw)' },
      { token: '{{appointment.user.email_signature}}', label: 'Assigned user signature' },
      { token: '{{calendar.name}}', label: 'Calendar name' },
    ],
  },
  {
    key: 'right_now',
    label: 'Right Now (send time)',
    note: 'Evaluated at send time, in the account time zone.',
    fields: [
      { token: '{{right_now.second}}', label: 'Second' },
      { token: '{{right_now.minute}}', label: 'Minute' },
      { token: '{{right_now.hour}}', label: 'Hour (24h)' },
      { token: '{{right_now.hour_ampm}}', label: 'Hour (AM/PM)' },
      { token: '{{right_now.ampm}}', label: 'AM / PM' },
      { token: '{{right_now.day_of_week}}', label: 'Day of week' },
      { token: '{{right_now.day}}', label: 'Day' },
      { token: '{{right_now.month}}', label: 'Month (number)' },
      { token: '{{right_now.month_name}}', label: 'Month name' },
      { token: '{{right_now.year}}', label: 'Year' },
      { token: '{{right_now.middle_endian_date}}', label: 'Date (MM/DD/YYYY)' },
      { token: '{{right_now.little_endian_date}}', label: 'Date (DD/MM/YYYY)' },
    ],
  },
  {
    key: 'attribution_first',
    label: 'Attribution (first touch)',
    note: 'From the contact’s first tracked session.',
    fields: [
      { token: '{{contact.attributionSource.sessionSource}}', label: 'Session source' },
      { token: '{{contact.attributionSource.url}}', label: 'Landing URL' },
      { token: '{{contact.attributionSource.campaign}}', label: 'Campaign' },
      { token: '{{contact.attributionSource.campaignId}}', label: 'Campaign ID' },
      { token: '{{contact.attributionSource.utmSource}}', label: 'UTM source' },
      { token: '{{contact.attributionSource.utmMedium}}', label: 'UTM medium' },
      { token: '{{contact.attributionSource.utmContent}}', label: 'UTM content' },
      { token: '{{contact.attributionSource.utmKeyword}}', label: 'UTM keyword' },
      { token: '{{contact.attributionSource.utmMatchType}}', label: 'UTM match type' },
      { token: '{{contact.attributionSource.referrer}}', label: 'Referrer' },
      { token: '{{contact.attributionSource.clickId}}', label: 'Ad click ID' },
      { token: '{{contact.attributionSource.adGroupId}}', label: 'Ad group ID' },
      { token: '{{contact.attributionSource.adId}}', label: 'Ad ID' },
    ],
  },
  {
    key: 'attribution_last',
    label: 'Attribution (latest touch)',
    note: 'From the contact’s most recent tracked session.',
    fields: [
      { token: '{{contact.lastAttributionSource.sessionSource}}', label: 'Session source' },
      { token: '{{contact.lastAttributionSource.url}}', label: 'Landing URL' },
      { token: '{{contact.lastAttributionSource.campaign}}', label: 'Campaign' },
      { token: '{{contact.lastAttributionSource.campaignId}}', label: 'Campaign ID' },
      { token: '{{contact.lastAttributionSource.utmSource}}', label: 'UTM source' },
      { token: '{{contact.lastAttributionSource.utmMedium}}', label: 'UTM medium' },
      { token: '{{contact.lastAttributionSource.utmCampaign}}', label: 'UTM campaign' },
      { token: '{{contact.lastAttributionSource.utmContent}}', label: 'UTM content' },
      { token: '{{contact.lastAttributionSource.utmKeyword}}', label: 'UTM keyword' },
      { token: '{{contact.lastAttributionSource.utmMatchType}}', label: 'UTM match type' },
      { token: '{{contact.lastAttributionSource.referrer}}', label: 'Referrer' },
      { token: '{{contact.lastAttributionSource.clickId}}', label: 'Ad click ID' },
      { token: '{{contact.lastAttributionSource.adGroupId}}', label: 'Ad group ID' },
      { token: '{{contact.lastAttributionSource.adId}}', label: 'Ad ID' },
    ],
  },
  {
    key: 'message',
    label: 'Message & Campaign',
    note: 'Used inside notification / reply templates.',
    fields: [
      { token: '{{message.body}}', label: 'Message body' },
      { token: '{{message.subject}}', label: 'Message subject' },
      { token: '{{campaign.event_date_time}}', label: 'Campaign event date & time' },
      { token: '{{campaign.event_date}}', label: 'Campaign event date' },
      { token: '{{campaign.event_time}}', label: 'Campaign event time' },
    ],
  },
  {
    key: 'invoice',
    label: 'Invoice',
    note: 'Only resolves in invoice emails / SMS.',
    fields: [
      { token: '{{invoice.name}}', label: 'Invoice name' },
      { token: '{{invoice.number}}', label: 'Invoice number' },
      { token: '{{invoice.title}}', label: 'Invoice title' },
      { token: '{{invoice.url}}', label: 'Invoice link' },
      { token: '{{invoice.issue_date}}', label: 'Issue date' },
      { token: '{{invoice.due_date}}', label: 'Due date' },
      { token: '{{invoice.sub_total}}', label: 'Subtotal' },
      { token: '{{invoice.discount_amount}}', label: 'Discount amount' },
      { token: '{{invoice.tax_amount}}', label: 'Tax amount' },
      { token: '{{invoice.total_amount}}', label: 'Total amount' },
      { token: '{{invoice.company.name}}', label: 'Company name' },
      { token: '{{invoice.company.phone}}', label: 'Company phone' },
      { token: '{{invoice.company.address}}', label: 'Company address' },
      { token: '{{invoice.company.city}}', label: 'Company city' },
      { token: '{{invoice.company.state}}', label: 'Company state' },
      { token: '{{invoice.company.country}}', label: 'Company country' },
      { token: '{{invoice.company.website}}', label: 'Company website' },
      { token: '{{invoice.company.logo}}', label: 'Company logo URL' },
      { token: '{{invoice.customer.name}}', label: 'Customer name' },
      { token: '{{invoice.customer.first_name}}', label: 'Customer first name' },
      { token: '{{invoice.customer.last_name}}', label: 'Customer last name' },
      { token: '{{invoice.customer.email}}', label: 'Customer email' },
      { token: '{{invoice.customer.phone}}', label: 'Customer phone' },
      { token: '{{invoice.customer.company}}', label: 'Customer company' },
      { token: '{{invoice.customer.address}}', label: 'Customer address' },
      { token: '{{invoice.customer.city}}', label: 'Customer city' },
      { token: '{{invoice.customer.state}}', label: 'Customer state' },
      { token: '{{invoice.customer.postal_code}}', label: 'Customer postal code' },
      { token: '{{invoice.sender.name}}', label: 'Sender name' },
      { token: '{{invoice.sender.email}}', label: 'Sender email' },
      { token: '{{invoice.card.brand}}', label: 'Card brand' },
      { token: '{{invoice.card.last4}}', label: 'Card last 4' },
    ],
  },
  {
    key: 'servicebooking',
    label: 'Service Booking',
    note: 'Service-menu bookings only.',
    fields: [
      { token: '{{servicebooking.title}}', label: 'Title' },
      { token: '{{servicebooking.start_time}}', label: 'Start time' },
      { token: '{{servicebooking.start_date}}', label: 'Start date' },
      { token: '{{servicebooking.end_time}}', label: 'End time' },
      { token: '{{servicebooking.only_end_date}}', label: 'End date only' },
      { token: '{{servicebooking.only_end_time}}', label: 'End time only' },
      { token: '{{servicebooking.day_of_week}}', label: 'Day of week' },
      { token: '{{servicebooking.month}}', label: 'Month (number)' },
      { token: '{{servicebooking.month_name}}', label: 'Month name' },
      { token: '{{servicebooking.timezone}}', label: 'Time zone' },
      { token: '{{servicebooking.total_price}}', label: 'Total price' },
      { token: '{{servicebooking.meeting_location}}', label: 'Meeting location' },
      { token: '{{servicebooking.meeting_location_name}}', label: 'Meeting location name' },
      { token: '{{servicebooking.reschedule_link}}', label: 'Reschedule link' },
      { token: '{{servicebooking.cancellation_link}}', label: 'Cancellation link' },
    ],
  },
  {
    key: 'courses',
    label: 'Courses',
    note: 'Membership / course notifications.',
    fields: [
      { token: '{{courses.categoryTitle}}', label: 'Category title' },
      { token: '{{courses.productTitle}}', label: 'Product title' },
      { token: '{{courses.postTitle}}', label: 'Post title' },
    ],
  },
]

// Every token in one flat list, for search.
export const ALL_MERGE_FIELDS = MERGE_FIELD_GROUPS.flatMap(g =>
  g.fields.map(f => ({ ...f, group: g.label, groupKey: g.key }))
)
